### ISSUE TITLE
get how many times a ticker's C() function has been called?

### ISSUE THREAD

**Issue by qibobo** [cloudfoundry/clock#5]
In some tests, for example as below. While the eventChan always has data to retrieve, so sometimes the ticker does not have a chance to run in a period, so func2 may not be called in time. How about add a function to the faketimer that we can get how many times the ticker.C() has been called. So after a certain times we want, then we start the assertion.
```
select {		
	case event := <-eventChan:
             func1()
	case <-ticker.C():	
            func2()		
}
```

**Comment by emalm** [comment]
Hey, @qibobo, do you think you could illustrate more explicitly how you would use that function in a test setup? I'm having a difficult time envisioning how it would be useful to you, and I suspect the rest of the Diego team would also like to understand that.

Thanks,
Eric

**Comment by qibobo** [comment]
@emalm my scenario is the code as below. In the for-loop, when case1 and case2 are both available, there is no priority, right? So func1 may have been executed some times while func2 does not have a change. In my test I need to guarantee that the func2 at least has been called once then to do test assertion.
```
for {
	select {
	case event := <-eventChan::
		func1()
	case <-ticker.C:
		func2()
	}
}
```

**Comment by mariash** [comment]
@qibobo please let us know if this would still be valuable to you? Could you please provide an example of the test how you would call the method and make an assertion? PRs are always welcome too!

**Comment by mariash** [comment]
@qibobo I am going to close this issue due to no response and how old it is. If you still have questions feel free to comment here or open a new issue.
