### ISSUE TITLE
Request to make dropping ticks optional

### ISSUE THREAD

**Issue by guoger** [cloudfoundry/clock#6]
https://github.com/cloudfoundry/clock/blob/02e53af36e6c978af692887ed449b74026d76fec/fakeclock/fake_timer.go#L79-L81

Can we make this behavior optional (configurable)? sometimes in tests, we want to make sure a receiver consumes **certain number of ticks** before we proceed. However with the possibility that tick may be dropped, we have no control of that, and have to introduce real time intervals between incrementing fake block, so that a slow receiver will eventually consumes that many ticks.

**Comment by n4wei** [comment]
Hi @guoger. Sorry for the late response. Can you please provide an example of the behavior you expect to see if it is no longer possible to skip sending on `ft.channel`? Would this behavior now be blocking until another goroutine reads from `ft.channel`?

**Comment by guoger** [comment]
@n4wei yes, i'd expect it to be blocking, so we can know deterministically number of ticks consumed by the receiver. (obviously this should be optional so the original behavior is preserved for other lib users)

Another request we have is to be able to label the timer, so when we have multiple timers created, we can explicitly wait for a specific watcher in test. for example, say we have 2 timers T_a and T_b, and we want to wait for T_b to start before performing some assertions in test. Instead of `WatiForNWatchers(2)`, we could `WaitForWatcherWithLabel("T_b")`. The benefit is two-fold:
- this comes handy when T_a may or may not start, and we only care about T_b
- when we introduce 3rd timer T_c, we don't need to change all existing test to be `WaitForNWatchers(3)`

let me know if these requests make sense. I'm happy to contribute as well.

**Comment by aminjam** [comment]
@guoger I am a bit unclear about how you would use this in a test code. It sounds like you would have to create a `fakeclock.NewTimer` somewhere in your codebase. We haven't needed to use something like this in our test files yet. Assuming this was implemented, what would a test example look like that utilizes this that we can't already do with the current interface?

**Comment by guoger** [comment]
I guess I'm mixing two requests in this thread and caused some miscommunication. Let's focus on dropping ticks for now.

Suppose i have following code
```
ticker := clock.NewTicker(time.Second)
for {
  select {
    case <-ticker:
      // periodic job
    case <-taskChan:
      // some heavy task
  }
}
```
and following code in test
```
clock.Increment(time.Second)
clock.Increment(time.Second)
clock.Increment(time.Second)
```

I'd like to be sure that periodic job is executed exactly 3 times. Although, with the possibility that tick may be dropped, this number is not deterministic.

hope this helps @aminjam 

as for the other request, i'll create another issue

**Comment by aminjam** [comment]
In a scenario where we have a slow consumer e.g. `some heavy task`, couldn't you use the fake version of the heavy task, this way you would know how many times this `timer.C()` was called? This is because the heavy task causes the select to be blocked and even if the ticker was not dropping on the floor, you still wouldn't be able to catch it. 

Though there is a small difference in timing, it seems like using a `Timer`, resetting it instead of a `Ticker`, and using `clock.WaitForWatcherAndIncrement()` in your tests sounds like it would achieve the behavior you want.

**Comment by guoger** [comment]
> you still wouldn't be able to catch it.

not sure i understood this correctly... if it's block, i would be sure that all the ticks are consumed deterministically, no?
otherwise i'll have to put a little pulse (real time) between each `increment`, which theoretically still doesn't make test deterministic. As for the "heavy task", it's part of the target we are testing, i.e. sending out heartbeat every tick, and doing real job with `taskChan`.

IMHO, adding a toggle-able behavior to fake timer would be less invasive for most users, rather than converting all the ticker to timer.

**Comment by n4wei** [comment]
@guoger could you please make a PR for this change in behavior? The old behavior where ticks can be dropped should be the default; and the new behavior where ticks are not dropped should be opt-in.

**Comment by sunjayBhatia** [comment]
closing issue in favor of a PR, we will accept this change but it isn't a priority for us to implement ourselves at this time
