### ISSUE TITLE
mirror URL not found

### ISSUE THREAD

**Issue by iamnande** [cloudfoundry/clock#7]
in our `go.mod` we have from a dependency on AppInsights from Microsoft:
```
code.cloudfoundry.org/clock v0.0.0-20180518195852-02e53af36e6c // indirect
```

however, we are currently unable to build projects that depend on AppInsights because of the following error:
```
$ <any go command that does building>
go: code.cloudfoundry.org/clock@v0.0.0-20180518195852-02e53af36e6c: unrecognized import path "code.cloudfoundry.org/clock" (parse https://code.cloudfoundry.org/clock?go-get=1: no go-import meta tags ())
go: error loading module requirements
```

there's also a nice [404 on godoc](https://godoc.org/code.cloudfoundry.org/clock) as well

halp?

**Comment by iamnande** [comment]
seems to have resolved itself? closing anyhow

**Comment by sunjayBhatia** [comment]
I believe there was an outage on the app that does the `code.cloudfoundry.org` redirects yesterday which is probably why you saw that
