### ISSUE TITLE
Please consider adding a semver compatible tag alongside existing tag

### ISSUE THREAD

**Issue by SamWhited** [cloudfoundry/clock#8]
Hello,

Go Modules now uses semver compatible tags (eg. `v1.0.0`, notice the "v" prefix). To make it easier to import this library from within projects that use modules, please consider adding a 'v' prefixed tag alongside the existing version tags. If I manually pin to your `1.0.0` tag, Go Modules replaces this with the commit hash, making it hard to keep track of what version I'm on so pinning to a semver version would make this much easier.

Thank you for your consideration.

**Comment by thaJeztah** [comment]
Actually, I think this is a bug in go mod; SemVer does _not_ require the `v` prefix; in fact, the prefix is _not_ SemVer; there was a proposal for a `SemVerTag` standard (which required `v` for tags), but that was removed in SemVer 1.0; https://github.com/semver/semver/issues/1#issuecomment-2605236

> ### Is “v1.2.3” a semantic version?
>
> No, “v1.2.3” is not a semantic version. However, prefixing a semantic version with a “v” is a common way (in English) to indicate it is a version number. Abbreviating “version” as “v” is often seen with version control. Example: git tag v1.2.3 -m "Release version 1.2.3", in which case “v1.2.3” is a tag name and the semantic version is “1.2.3”.

I see they had some discussion about this in 2015; https://github.com/golang/go/issues/12302#issuecomment-134993195

**Comment by SamWhited** [comment]
Quoted from the swarmkit discussion:

> Yes, sadly the v is deliberately required (amusingly, one of the reasons v was used is because Docker used it). I can't find the discussion right now, but I think only one was used because they didn't want to deal with the case where someone mixes versions and pins the same version to two different commits (eg. 1.0.0 and v1.0.0 on the next commit). Which do you pick? In the end, I believe they decided it was easier to just support a single standard and let the Go community normalize on that in the same way that gofmt isn't everybody's favorite format, but the consistency is worth it.

**Comment by heyjcollins** [comment]
Hey @SamWhited - unfortunately we're not in a position with regards to resources and given our priorities to make this change so I'm going to close it out. Apologies.

**Comment by thaJeztah** [comment]
Does that mean this repository is no longer maintained (and should be archived)?

**Comment by heyjcollins** [comment]
Hey @SamWhited - Actually, we intend to continue to maintain this repo. And after further discussion and review, we've decided to apply semver. We'll make the change and update the readme accordingly in the next week or so.
